version: '3.1'

services:
  postgres-db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgrestodoapp

  todoserver:
    build:
      context: ../../../.
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres-db
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/todo

  todoclient:
    build:
      context: ../../../react-todo/.
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
    - "3000:3000"