version: '3.1'

services:
  postgres-db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgrestodoapp

  todoserver:
    build:
      context: ../../../.
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres-db
    expose:
      - 8088
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/todo

volumes:
  postgres-data: