version: '3.1'

services:
  postgres-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgrestodoapp

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8085